project:
  type: website
  output-dir: docs

website:
  title: "torus visualizations"
  navbar:
    left:
      - href: 'http://euclid.nmu.edu/~joshthom'
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    html-math-method: mathjax
    css: styles.css
    toc: false

filters:
  - pseudocode

